### ISSUE TITLE
Possible to do express+passport+twitter authentication without cookies?

### ISSUE THREAD

**Issue by zettam** [jaredhanson/passport-twitter#77] opened 2016-02-29 01:46 UTC
^ as the question asks  - possible?
If so, a sample would be perfect!

**Comment by BryanConradHart** [comment] 2016-04-02 01:14
I would also like to know.
I'm writing an API with restify/passport-restify. Since our API clients won't have cookies, I'm hoping to capture the twitter access token and issue my own token to our client.
I've got it working with passport-facebook, I was hoping that twitter would be similar, but I ran into this issue.

**Comment by jaredhanson** [comment] 2016-04-02 02:24
Duplicate of #74

**Closed by jaredhanson** 2016-04-02 02:24 UTC
