### ISSUE TITLE
Route middleware functionality not working

### ISSUE THREAD

**Issue by emjoseph** [jaredhanson/passport-twitter#51] opened 2014-11-20 04:26 UTC
So I'm running twitter-passport w/ Express 4.0, but the route middleware functionality advertised isn't working for me. The reason is that I'm using this module in conjunction with an iOS app and I want to send a JSON object to the server instead of a simple redirect. Is there are anything wrong with my syntax?

Here's sample code:

```
app.get('/auth/twitterX/callback', passport.authenticate('twitter'),function(req,res){
    console.log("Made it past passport authen");    
    res.json({"status":"success"});
});
```

Basically I never get the console.log message displayed.

**Comment by bcharbonnier** [comment] 2015-03-11 21:52
I think I have the exact same problem. w/ Express 4 (4.12.2) at the time Twitter should call us back on the callbackUrl, it simply timeout.

Myself, I am using `res.redirect` from within my callback, this is the only difference compare to @emjoseph example. I don't use `res.json`

**Comment by jaredhanson** [comment] 2018-12-05 01:20
Duplicate of #46

**Closed** 2021-11-12 23:07 UTC
Labels: duplicate, question
